services:
  db:
    image: postgres:17.6
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - contester-net
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    restart: unless-stopped

  php:
    build:
      context: php
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html/
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini 
    depends_on:
      - db
    networks:
      - contester-net
    restart: unless-stopped

  web:
    image: nginx:1.26
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - contester-net
    restart: unless-stopped

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  runner:
    build:
      context: runner
    environment:
      RUNNER_PGSQL_CONNECTION: "host=db dbname=contester user=postgres password=postgres"
    networks:
      - contester-net
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db-data:

networks:
  contester-net: