services:
  db:
    image: postgres:15.14
    container_name: db
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - contester-net
    restart: unless-stopped

  php:
    build:
      dockerfile: Dockerfile.php
    container_name: contester_php
    volumes:
      - ./app:/var/www/html/
    depends_on:
      - db
    networks:
      - contester-net
    restart: unless-stopped

  web:
    image: nginx:1.22.1
    container_name: contester_nginx
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - contester-net
    restart: unless-stopped

volumes:
  db-data:

networks:
  contester-net: